### ISSUE TITLE
post-thumbnail -BUG

### ISSUE THREAD

**Issue by Carseason** [ihacklog/hacklog-remote-attachment#2]
通过插件上传附件,文章略缩图以及网站icon等引用媒体库的地方依然导向原链接,
例如:a.com使用了插件,ftp链接了a.a.com,在文章略缩图等部分媒体附件依然指向a.com而非a.a.com

**Comment by Caeseason** [comment]
![eq esgi s p49 i9wfwul w](https://user-images.githubusercontent.com/25239238/36656384-20fae10a-1b03-11e8-84c5-5bdcb20041f8.jpg)
目前 使用的是wordpress4.9.4,PHP7.2

**Comment by ihacklog** [comment]
fixed in d9eb1b9315baf95bddce14d43344fe742a9f9364

**Comment by ihacklog** [comment]
已更新到 1.3.2 https://downloads.wordpress.org/plugin/hacklog-remote-attachment.1.3.2.zip
